import { Expense } from "./expenses.types";

export const mockExpenses: Expense[] = [
  {
    id: "1",
    title: "Supermercado",
    amount: 45000,
    category: "Comida",
    date: "2026-02-01",
    type: "expense",
  },
  {
    id: "2",
    title: "Arriendo",
    amount: 350000,
    category: "Vivienda",
    date: "2026-02-01",
    type: "expense",
  },
  {
    id: "3",
    title: "Spotify",
    amount: 4990,
    category: "Suscripciones",
    date: "2026-02-05",
    type: "expense",
  },
  {
    id: "4",
    title: "Sueldo",
    amount: 1000000,
    category: "Salario",
    date: "2026-02-01",
    type: "income",
  },
  {
    id: "5",
    title: "Reembolso Vuelo",
    amount: 85000,
    category: "Viajes",
    date: "2026-02-06",
    type: "income",
  },
  {
    id: "6",
    title: "Café",
    amount: 3990,
    category: "Comida",
    date: "2026-02-07",
    type: "expense",
  },
  {
    id: "7",
    title: "Venta bicicleta",
    amount: 120000,
    category: "",
    date: "2026-02-08",
    type: "income",
  },
];
