import { Expense } from "./expenses.types";

export const mockExpenses: Expense[] = [
  {
    id: "1",
    title: "Reembolso Viaje Julio",
    amount: 38391,
    categories: ["Reembolsos", "Viajes", "Trabajo"],
    date: "2026-09-11T04:52",
    type: "income",
    affectsBalance: true,
    accountId: "6",
    pending: false,
  },
  {
    id: "2",
    title: "Compra Ferreteria",
    amount: 8900,
    categories: ["Otros"],
    date: "2026-09-08T15:20",
    type: "expense",
    affectsBalance: true,
    accountId: "5",
    paymentDay: 5,
    pending: false,
  },
  {
    id: "3",
    title: "Compra Farmacias Ahumada",
    amount: 23795,
    categories: ["Salud"],
    date: "2026-09-07T22:43",
    type: "expense",
    affectsBalance: true,
    accountId: "5",
    paymentDay: 5,
    pending: false,
  },
  {
    id: "4",
    title: "Balance Inicial cuenta de ahorro vivienda",
    amount: 1143000,
    categories: ["Ahorros", "Vivienda", "UF"],
    date: "2026-09-01T00:00",
    type: "income",
    affectsBalance: true,
    accountId: "1",
    pending: false,
  },
  {
    id: "5",
    title: "Balance Inicial Cuenta Rut",
    amount: 28327,
    categories: [],
    date: "2026-09-01T00:00",
    type: "income",
    affectsBalance: true,
    accountId: "6",
    pending: false,
  },
  {
    id: "6",
    title: "Saldo Inicial MACH",
    amount: 885572,
    categories: [],
    date: "2026-09-01T00:00",
    type: "income",
    affectsBalance: true,
    accountId: "4",
    pending: false,
  },
  {
    id: "7",
    title: "Saldo Inicial Copec Pay",
    amount: 2000000,
    categories: ["Salario"],
    date: "2026-09-01T00:00",
    type: "income",
    affectsBalance: true,
    accountId: "3",
    pending: false,
  },
];
